# Generated by Django 3.1.2 on 2020-10-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('category', models.CharField(choices=[('cake', 'cake'), ('drink', 'drink')], default='cake', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
