# Generated by Django 3.1.2 on 2020-10-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('cart', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
