# Generated by Django 3.1.2 on 2020-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201023_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryFee',
            field=models.FloatField(default=0),
        ),
    ]
