# Generated by Django 3.1.2 on 2020-10-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_deliveryfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.CharField(max_length=10000),
        ),
    ]
